language: node_js
node_js:
- '5'
sudo: false
addons:
  firefox: latest
notifications:
  email: false
before_install:
  - cd ..
  - git clone --depth=50 --branch=master https://github.com/jupyterlab/jupyterlab.git
  - cd jupyterlab
install:
  - npm install fs-extra child-process path sort-package-json
  - npm run addsibling $TRAVIS_BUILD_DIR && npm install
  - npm run build
before_script:
  - cd packages && cd `basename $TRAVIS_BUILD_DIR`
  - npm run build:test
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm test
